//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rfc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="curp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secciones" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="seccionesHistoricas" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id_sucursal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="t_relacion" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="t_ubicacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ef_ubic_especifica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rfc",
    "curp",
    "nit",
    "secciones",
    "seccionesHistoricas",
    "idSucursal",
    "usuario",
    "password",
    "tRelacion",
    "tUbicacion",
    "efUbicEspecifica"
})
@XmlRootElement(name = "datosEntrada")
public class DatosEntrada {

    @XmlElement(required = true)
    private String rfc;
    private String curp;
    private String nit;
    private List<String> secciones;
    private List<String> seccionesHistoricas;
    @XmlElement(name = "id_sucursal")
    private String idSucursal;
    @XmlElement(required = true)
    private String usuario;
    @XmlElement(required = true)
    private String password;
    @XmlElement(name = "t_relacion")
    private List<String> tRelacion;
    @XmlElement(name = "t_ubicacion")
    private String tUbicacion;
    @XmlElement(name = "ef_ubic_especifica")
    private String efUbicEspecifica;

    /**
     * Gets the value of the rfc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfc() {
        return rfc;
    }

    /**
     * Sets the value of the rfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfc(String value) {
        this.rfc = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the nit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNit() {
        return nit;
    }

    /**
     * Sets the value of the nit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNit(String value) {
        this.nit = value;
    }

    /**
     * Gets the value of the secciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSecciones() {
        if (secciones == null) {
            secciones = new ArrayList<String>();
        }
        return this.secciones;
    }

    /**
     * Gets the value of the seccionesHistoricas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seccionesHistoricas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeccionesHistoricas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSeccionesHistoricas() {
        if (seccionesHistoricas == null) {
            seccionesHistoricas = new ArrayList<String>();
        }
        return this.seccionesHistoricas;
    }

    /**
     * Gets the value of the idSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSucursal() {
        return idSucursal;
    }

    /**
     * Sets the value of the idSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSucursal(String value) {
        this.idSucursal = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the tRelacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tRelacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRelacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTRelacion() {
        if (tRelacion == null) {
            tRelacion = new ArrayList<String>();
        }
        return this.tRelacion;
    }

    /**
     * Gets the value of the tUbicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTUbicacion() {
        return tUbicacion;
    }

    /**
     * Sets the value of the tUbicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTUbicacion(String value) {
        this.tUbicacion = value;
    }

    /**
     * Gets the value of the efUbicEspecifica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfUbicEspecifica() {
        return efUbicEspecifica;
    }

    /**
     * Sets the value of the efUbicEspecifica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfUbicEspecifica(String value) {
        this.efUbicEspecifica = value;
    }

    @Override
    public String toString() {
        return "DatosEntrada{" +
                "rfc='" + rfc + '\'' +
                ", curp='" + curp + '\'' +
                ", nit='" + nit + '\'' +
                ", secciones=" + secciones +
                ", seccionesHistoricas=" + seccionesHistoricas +
                ", idSucursal='" + idSucursal + '\'' +
                ", usuario='" + usuario + '\'' +
                ", password='" + password + '\'' +
                ", tRelacion=" + tRelacion +
                ", tUbicacion='" + tUbicacion + '\'' +
                ", efUbicEspecifica='" + efUbicEspecifica + '\'' +
                '}';
    }
}
