//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grupoEmpresa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grupoEmpresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rfc_soc_controladora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nom_soc_controladora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfc_soc_controlada" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nom_soc_controlada" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="num_gpo_consol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_cons_soc_control" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_inc_soc_control" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grupoEmpresa", propOrder = {
    "rfcSocControladora",
    "nomSocControladora",
    "rfcSocControlada",
    "nomSocControlada",
    "numGpoConsol",
    "fConsSocControl",
    "fIncSocControl"
})
public class GrupoEmpresa {

    @XmlElement(name = "rfc_soc_controladora", required = true)
    private String rfcSocControladora;
    @XmlElement(name = "nom_soc_controladora", required = true)
    private String nomSocControladora;
    @XmlElement(name = "rfc_soc_controlada", required = true)
    private String rfcSocControlada;
    @XmlElement(name = "nom_soc_controlada", required = true)
    private String nomSocControlada;
    @XmlElement(name = "num_gpo_consol", required = true)
    private String numGpoConsol;
    @XmlElement(name = "f_cons_soc_control", required = true)
    private String fConsSocControl;
    @XmlElement(name = "f_inc_soc_control", required = true)
    private String fIncSocControl;

    /**
     * Gets the value of the rfcSocControladora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcSocControladora() {
        return rfcSocControladora;
    }

    /**
     * Sets the value of the rfcSocControladora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcSocControladora(String value) {
        this.rfcSocControladora = value;
    }

    /**
     * Gets the value of the nomSocControladora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomSocControladora() {
        return nomSocControladora;
    }

    /**
     * Sets the value of the nomSocControladora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomSocControladora(String value) {
        this.nomSocControladora = value;
    }

    /**
     * Gets the value of the rfcSocControlada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcSocControlada() {
        return rfcSocControlada;
    }

    /**
     * Sets the value of the rfcSocControlada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcSocControlada(String value) {
        this.rfcSocControlada = value;
    }

    /**
     * Gets the value of the nomSocControlada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomSocControlada() {
        return nomSocControlada;
    }

    /**
     * Sets the value of the nomSocControlada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomSocControlada(String value) {
        this.nomSocControlada = value;
    }

    /**
     * Gets the value of the numGpoConsol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumGpoConsol() {
        return numGpoConsol;
    }

    /**
     * Sets the value of the numGpoConsol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumGpoConsol(String value) {
        this.numGpoConsol = value;
    }

    /**
     * Gets the value of the fConsSocControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFConsSocControl() {
        return fConsSocControl;
    }

    /**
     * Sets the value of the fConsSocControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFConsSocControl(String value) {
        this.fConsSocControl = value;
    }

    /**
     * Gets the value of the fIncSocControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIncSocControl() {
        return fIncSocControl;
    }

    /**
     * Sets the value of the fIncSocControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIncSocControl(String value) {
        this.fIncSocControl = value;
    }

    @Override
    public String toString() {
        return "GrupoEmpresa{" +
                "rfcSocControladora='" + rfcSocControladora + '\'' +
                ", nomSocControladora='" + nomSocControladora + '\'' +
                ", rfcSocControlada='" + rfcSocControlada + '\'' +
                ", nomSocControlada='" + nomSocControlada + '\'' +
                ", numGpoConsol='" + numGpoConsol + '\'' +
                ", fConsSocControl='" + fConsSocControl + '\'' +
                ", fIncSocControl='" + fIncSocControl + '\'' +
                '}';
    }
}
