//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RFC_Original" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RFC_Vigente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RFC_Solicitado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="boid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Identificacion" type="{http://www.sat.gob.mx/IdCInterno/messages}identificacion" minOccurs="0"/>
 *         &lt;element name="Ubicacion" type="{http://www.sat.gob.mx/IdCInterno/messages}ubicacion" minOccurs="0"/>
 *         &lt;element name="Obligaciones" type="{http://www.sat.gob.mx/IdCInterno/messages}obligacion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Regimenes" type="{http://www.sat.gob.mx/IdCInterno/messages}regimen" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Roles" type="{http://www.sat.gob.mx/IdCInterno/messages}rol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Actividades" type="{http://www.sat.gob.mx/IdCInterno/messages}actividad" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Rep_Legales" type="{http://www.sat.gob.mx/IdCInterno/messages}rep_legal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Sucursales" type="{http://www.sat.gob.mx/IdCInterno/messages}sucursal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Mensajes" type="{http://www.sat.gob.mx/IdCInterno/messages}mensajes" minOccurs="0"/>
 *         &lt;element name="GrupoEmpresas" type="{http://www.sat.gob.mx/IdCInterno/messages}grupoEmpresa" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Relaciones" type="{http://www.sat.gob.mx/IdCInterno/messages}relacion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UbicacionEspecifica" type="{http://www.sat.gob.mx/IdCInterno/messages}ubicacion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RFCHistoricos" type="{http://www.sat.gob.mx/IdCInterno/messages}rfcHistorico" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Patentes" type="{http://www.sat.gob.mx/IdCInterno/messages}patente" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Sectores" type="{http://www.sat.gob.mx/IdCInterno/messages}sector" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rfcOriginal",
    "rfcVigente",
    "rfcSolicitado",
    "boid",
    "personid",
    "identificacion",
    "ubicacion",
    "obligaciones",
    "regimenes",
    "roles",
    "actividades",
    "repLegales",
    "sucursales",
    "mensajes",
    "grupoEmpresas",
    "relaciones",
    "ubicacionEspecifica",
    "rfcHistoricos",
    "patentes",
    "sectores"
})
@XmlRootElement(name = "IdCInterno")
public class IdCInterno {

    @XmlElement(name = "RFC_Original")
    private String rfcOriginal;
    @XmlElement(name = "RFC_Vigente")
    private String rfcVigente;
    @XmlElement(name = "RFC_Solicitado")
    private String rfcSolicitado;
    private String boid;
    private String personid;
    @XmlElement(name = "Identificacion")
    private Identificacion identificacion;
    @XmlElement(name = "Ubicacion")
    private Ubicacion ubicacion;
    @XmlElement(name = "Obligaciones")
    private List<Obligacion> obligaciones;
    @XmlElement(name = "Regimenes")
    private List<Regimen> regimenes;
    @XmlElement(name = "Roles")
    private List<Rol> roles;
    @XmlElement(name = "Actividades")
    private List<Actividad> actividades;
    @XmlElement(name = "Rep_Legales")
    private List<RepLegal> repLegales;
    @XmlElement(name = "Sucursales")
    private List<Sucursal> sucursales;
    @XmlElement(name = "Mensajes")
    private Mensajes mensajes;
    @XmlElement(name = "GrupoEmpresas")
    private List<GrupoEmpresa> grupoEmpresas;
    @XmlElement(name = "Relaciones")
    private List<Relacion> relaciones;
    @XmlElement(name = "UbicacionEspecifica")
    private List<Ubicacion> ubicacionEspecifica;
    @XmlElement(name = "RFCHistoricos")
    private List<RfcHistorico> rfcHistoricos;
    @XmlElement(name = "Patentes")
    private List<Patente> patentes;
    @XmlElement(name = "Sectores")
    private List<Sector> sectores;

    /**
     * Gets the value of the rfcOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFCOriginal() {
        return rfcOriginal;
    }

    /**
     * Sets the value of the rfcOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFCOriginal(String value) {
        this.rfcOriginal = value;
    }

    /**
     * Gets the value of the rfcVigente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFCVigente() {
        return rfcVigente;
    }

    /**
     * Sets the value of the rfcVigente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFCVigente(String value) {
        this.rfcVigente = value;
    }

    /**
     * Gets the value of the rfcSolicitado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFCSolicitado() {
        return rfcSolicitado;
    }

    /**
     * Sets the value of the rfcSolicitado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFCSolicitado(String value) {
        this.rfcSolicitado = value;
    }

    /**
     * Gets the value of the boid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoid() {
        return boid;
    }

    /**
     * Sets the value of the boid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoid(String value) {
        this.boid = value;
    }

    /**
     * Gets the value of the personid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonid() {
        return personid;
    }

    /**
     * Sets the value of the personid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonid(String value) {
        this.personid = value;
    }

    /**
     * Gets the value of the identificacion property.
     * 
     * @return
     *     possible object is
     *     {@link Identificacion }
     *     
     */
    public Identificacion getIdentificacion() {
        return identificacion;
    }

    /**
     * Sets the value of the identificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identificacion }
     *     
     */
    public void setIdentificacion(Identificacion value) {
        this.identificacion = value;
    }

    /**
     * Gets the value of the ubicacion property.
     * 
     * @return
     *     possible object is
     *     {@link Ubicacion }
     *     
     */
    public Ubicacion getUbicacion() {
        return ubicacion;
    }

    /**
     * Sets the value of the ubicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ubicacion }
     *     
     */
    public void setUbicacion(Ubicacion value) {
        this.ubicacion = value;
    }

    /**
     * Gets the value of the obligaciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obligaciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObligaciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Obligacion }
     * 
     * 
     */
    public List<Obligacion> getObligaciones() {
        if (obligaciones == null) {
            obligaciones = new ArrayList<Obligacion>();
        }
        return this.obligaciones;
    }

    /**
     * Gets the value of the regimenes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regimenes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegimenes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Regimen }
     * 
     * 
     */
    public List<Regimen> getRegimenes() {
        if (regimenes == null) {
            regimenes = new ArrayList<Regimen>();
        }
        return this.regimenes;
    }

    /**
     * Gets the value of the roles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rol }
     * 
     * 
     */
    public List<Rol> getRoles() {
        if (roles == null) {
            roles = new ArrayList<Rol>();
        }
        return this.roles;
    }

    /**
     * Gets the value of the actividades property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actividades property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActividades().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actividad }
     * 
     * 
     */
    public List<Actividad> getActividades() {
        if (actividades == null) {
            actividades = new ArrayList<Actividad>();
        }
        return this.actividades;
    }

    /**
     * Gets the value of the repLegales property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repLegales property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepLegales().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepLegal }
     * 
     * 
     */
    public List<RepLegal> getRepLegales() {
        if (repLegales == null) {
            repLegales = new ArrayList<RepLegal>();
        }
        return this.repLegales;
    }

    /**
     * Gets the value of the sucursales property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sucursales property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSucursales().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sucursal }
     * 
     * 
     */
    public List<Sucursal> getSucursales() {
        if (sucursales == null) {
            sucursales = new ArrayList<Sucursal>();
        }
        return this.sucursales;
    }

    /**
     * Gets the value of the mensajes property.
     * 
     * @return
     *     possible object is
     *     {@link Mensajes }
     *     
     */
    public Mensajes getMensajes() {
        return mensajes;
    }

    /**
     * Sets the value of the mensajes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mensajes }
     *     
     */
    public void setMensajes(Mensajes value) {
        this.mensajes = value;
    }

    /**
     * Gets the value of the grupoEmpresas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoEmpresas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoEmpresas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoEmpresa }
     * 
     * 
     */
    public List<GrupoEmpresa> getGrupoEmpresas() {
        if (grupoEmpresas == null) {
            grupoEmpresas = new ArrayList<GrupoEmpresa>();
        }
        return this.grupoEmpresas;
    }

    /**
     * Gets the value of the relaciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relaciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelaciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relacion }
     * 
     * 
     */
    public List<Relacion> getRelaciones() {
        if (relaciones == null) {
            relaciones = new ArrayList<Relacion>();
        }
        return this.relaciones;
    }

    /**
     * Gets the value of the ubicacionEspecifica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ubicacionEspecifica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUbicacionEspecifica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ubicacion }
     * 
     * 
     */
    public List<Ubicacion> getUbicacionEspecifica() {
        if (ubicacionEspecifica == null) {
            ubicacionEspecifica = new ArrayList<Ubicacion>();
        }
        return this.ubicacionEspecifica;
    }

    /**
     * Gets the value of the rfcHistoricos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rfcHistoricos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRFCHistoricos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RfcHistorico }
     * 
     * 
     */
    public List<RfcHistorico> getRFCHistoricos() {
        if (rfcHistoricos == null) {
            rfcHistoricos = new ArrayList<RfcHistorico>();
        }
        return this.rfcHistoricos;
    }

    /**
     * Gets the value of the patentes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patentes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatentes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Patente }
     * 
     * 
     */
    public List<Patente> getPatentes() {
        if (patentes == null) {
            patentes = new ArrayList<Patente>();
        }
        return this.patentes;
    }

    /**
     * Gets the value of the sectores property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectores property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectores().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     * 
     * 
     */
    public List<Sector> getSectores() {
        if (sectores == null) {
            sectores = new ArrayList<Sector>();
        }
        return this.sectores;
    }

    @Override
    public String toString() {
        return "IdCInterno{" +
                "rfcOriginal='" + rfcOriginal + '\'' +
                ", rfcVigente='" + rfcVigente + '\'' +
                ", rfcSolicitado='" + rfcSolicitado + '\'' +
                ", boid='" + boid + '\'' +
                ", personid='" + personid + '\'' +
                ", identificacion=" + identificacion +
                ", ubicacion=" + ubicacion +
                ", obligaciones=" + obligaciones +
                ", regimenes=" + regimenes +
                ", roles=" + roles +
                ", actividades=" + actividades +
                ", repLegales=" + repLegales +
                ", sucursales=" + sucursales +
                ", mensajes=" + mensajes +
                ", grupoEmpresas=" + grupoEmpresas +
                ", relaciones=" + relaciones +
                ", ubicacionEspecifica=" + ubicacionEspecifica +
                ", rfcHistoricos=" + rfcHistoricos +
                ", patentes=" + patentes +
                ", sectores=" + sectores +
                '}';
    }
}
