//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identificacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identificacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="t_persona" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="c_Segmento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="d_Segmento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CURP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Razon_Soc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="t_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ap_Paterno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ap_Materno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Nom_Comercial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_Nacimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_Constitucion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Nacionalidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_Ini_Opers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_Sit_Cont" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_det_Sit_Cont" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Sit_Cont" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_Sit_Cont" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_Sit_Dom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Sit_Dom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_Sit_Cont_Dom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Sit_Cont_Dom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pais_Origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DF_Tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DF_Folio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DF_F_Inicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DF_F_Fin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identificacion", propOrder = {
    "tPersona",
    "cSegmento",
    "dSegmento",
    "curp",
    "nit",
    "razonSoc",
    "tSociedad",
    "nombre",
    "apPaterno",
    "apMaterno",
    "nomComercial",
    "fNacimiento",
    "fConstitucion",
    "nacionalidad",
    "fIniOpers",
    "cSitCont",
    "cDetSitCont",
    "dSitCont",
    "fSitCont",
    "cSitDom",
    "dSitDom",
    "cSitContDom",
    "dSitContDom",
    "paisOrigen",
    "dfTipo",
    "dfFolio",
    "dffInicio",
    "dffFin",
    "email"
})
public class Identificacion {

    @XmlElement(name = "t_persona")
    private String tPersona;
    @XmlElement(name = "c_Segmento")
    private String cSegmento;
    @XmlElement(name = "d_Segmento")
    private String dSegmento;
    @XmlElement(name = "CURP")
    private String curp;
    @XmlElement(name = "NIT", required = true)
    private String nit;
    @XmlElement(name = "Razon_Soc")
    private String razonSoc;
    @XmlElement(name = "t_Sociedad")
    private String tSociedad;
    @XmlElement(name = "Nombre")
    private String nombre;
    @XmlElement(name = "Ap_Paterno")
    private String apPaterno;
    @XmlElement(name = "Ap_Materno")
    private String apMaterno;
    @XmlElement(name = "Nom_Comercial")
    private String nomComercial;
    @XmlElement(name = "f_Nacimiento")
    private String fNacimiento;
    @XmlElement(name = "f_Constitucion")
    private String fConstitucion;
    @XmlElement(name = "Nacionalidad")
    private String nacionalidad;
    @XmlElement(name = "f_Ini_Opers", required = true)
    private String fIniOpers;
    @XmlElement(name = "c_Sit_Cont", required = true)
    private String cSitCont;
    @XmlElement(name = "c_det_Sit_Cont", required = true)
    private String cDetSitCont;
    @XmlElement(name = "d_Sit_Cont", required = true)
    private String dSitCont;
    @XmlElement(name = "f_Sit_Cont", required = true)
    private String fSitCont;
    @XmlElement(name = "c_Sit_Dom", required = true)
    private String cSitDom;
    @XmlElement(name = "d_Sit_Dom", required = true)
    private String dSitDom;
    @XmlElement(name = "c_Sit_Cont_Dom", required = true)
    private String cSitContDom;
    @XmlElement(name = "d_Sit_Cont_Dom", required = true)
    private String dSitContDom;
    @XmlElement(name = "Pais_Origen", required = true)
    private String paisOrigen;
    @XmlElement(name = "DF_Tipo", required = true)
    private String dfTipo;
    @XmlElement(name = "DF_Folio", required = true)
    private String dfFolio;
    @XmlElement(name = "DF_F_Inicio", required = true)
    private String dffInicio;
    @XmlElement(name = "DF_F_Fin", required = true)
    private String dffFin;
    private String email;

    /**
     * Gets the value of the tPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPersona() {
        return tPersona;
    }

    /**
     * Sets the value of the tPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPersona(String value) {
        this.tPersona = value;
    }

    /**
     * Gets the value of the cSegmento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSegmento() {
        return cSegmento;
    }

    /**
     * Sets the value of the cSegmento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSegmento(String value) {
        this.cSegmento = value;
    }

    /**
     * Gets the value of the dSegmento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSegmento() {
        return dSegmento;
    }

    /**
     * Sets the value of the dSegmento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSegmento(String value) {
        this.dSegmento = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURP() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURP(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the nit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIT() {
        return nit;
    }

    /**
     * Sets the value of the nit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIT(String value) {
        this.nit = value;
    }

    /**
     * Gets the value of the razonSoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazonSoc() {
        return razonSoc;
    }

    /**
     * Sets the value of the razonSoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazonSoc(String value) {
        this.razonSoc = value;
    }

    /**
     * Gets the value of the tSociedad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSociedad() {
        return tSociedad;
    }

    /**
     * Sets the value of the tSociedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSociedad(String value) {
        this.tSociedad = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apPaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApPaterno() {
        return apPaterno;
    }

    /**
     * Sets the value of the apPaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApPaterno(String value) {
        this.apPaterno = value;
    }

    /**
     * Gets the value of the apMaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApMaterno() {
        return apMaterno;
    }

    /**
     * Sets the value of the apMaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApMaterno(String value) {
        this.apMaterno = value;
    }

    /**
     * Gets the value of the nomComercial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomComercial() {
        return nomComercial;
    }

    /**
     * Sets the value of the nomComercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomComercial(String value) {
        this.nomComercial = value;
    }

    /**
     * Gets the value of the fNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNacimiento() {
        return fNacimiento;
    }

    /**
     * Sets the value of the fNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNacimiento(String value) {
        this.fNacimiento = value;
    }

    /**
     * Gets the value of the fConstitucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFConstitucion() {
        return fConstitucion;
    }

    /**
     * Sets the value of the fConstitucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFConstitucion(String value) {
        this.fConstitucion = value;
    }

    /**
     * Gets the value of the nacionalidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacionalidad() {
        return nacionalidad;
    }

    /**
     * Sets the value of the nacionalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacionalidad(String value) {
        this.nacionalidad = value;
    }

    /**
     * Gets the value of the fIniOpers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIniOpers() {
        return fIniOpers;
    }

    /**
     * Sets the value of the fIniOpers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIniOpers(String value) {
        this.fIniOpers = value;
    }

    /**
     * Gets the value of the cSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitCont() {
        return cSitCont;
    }

    /**
     * Sets the value of the cSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitCont(String value) {
        this.cSitCont = value;
    }

    /**
     * Gets the value of the cDetSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDetSitCont() {
        return cDetSitCont;
    }

    /**
     * Sets the value of the cDetSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDetSitCont(String value) {
        this.cDetSitCont = value;
    }

    /**
     * Gets the value of the dSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitCont() {
        return dSitCont;
    }

    /**
     * Sets the value of the dSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitCont(String value) {
        this.dSitCont = value;
    }

    /**
     * Gets the value of the fSitCont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSitCont() {
        return fSitCont;
    }

    /**
     * Sets the value of the fSitCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSitCont(String value) {
        this.fSitCont = value;
    }

    /**
     * Gets the value of the cSitDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitDom() {
        return cSitDom;
    }

    /**
     * Sets the value of the cSitDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitDom(String value) {
        this.cSitDom = value;
    }

    /**
     * Gets the value of the dSitDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitDom() {
        return dSitDom;
    }

    /**
     * Sets the value of the dSitDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitDom(String value) {
        this.dSitDom = value;
    }

    /**
     * Gets the value of the cSitContDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSitContDom() {
        return cSitContDom;
    }

    /**
     * Sets the value of the cSitContDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSitContDom(String value) {
        this.cSitContDom = value;
    }

    /**
     * Gets the value of the dSitContDom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSitContDom() {
        return dSitContDom;
    }

    /**
     * Sets the value of the dSitContDom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSitContDom(String value) {
        this.dSitContDom = value;
    }

    /**
     * Gets the value of the paisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaisOrigen() {
        return paisOrigen;
    }

    /**
     * Sets the value of the paisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaisOrigen(String value) {
        this.paisOrigen = value;
    }

    /**
     * Gets the value of the dfTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFTipo() {
        return dfTipo;
    }

    /**
     * Sets the value of the dfTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFTipo(String value) {
        this.dfTipo = value;
    }

    /**
     * Gets the value of the dfFolio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFFolio() {
        return dfFolio;
    }

    /**
     * Sets the value of the dfFolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFFolio(String value) {
        this.dfFolio = value;
    }

    /**
     * Gets the value of the dffInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFFInicio() {
        return dffInicio;
    }

    /**
     * Sets the value of the dffInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFFInicio(String value) {
        this.dffInicio = value;
    }

    /**
     * Gets the value of the dffFin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFFFin() {
        return dffFin;
    }

    /**
     * Sets the value of the dffFin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFFFin(String value) {
        this.dffFin = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    @Override
    public String toString() {
        return "Identificacion{" +
                "tPersona='" + tPersona + '\'' +
                ", cSegmento='" + cSegmento + '\'' +
                ", dSegmento='" + dSegmento + '\'' +
                ", curp='" + curp + '\'' +
                ", nit='" + nit + '\'' +
                ", razonSoc='" + razonSoc + '\'' +
                ", tSociedad='" + tSociedad + '\'' +
                ", nombre='" + nombre + '\'' +
                ", apPaterno='" + apPaterno + '\'' +
                ", apMaterno='" + apMaterno + '\'' +
                ", nomComercial='" + nomComercial + '\'' +
                ", fNacimiento='" + fNacimiento + '\'' +
                ", fConstitucion='" + fConstitucion + '\'' +
                ", nacionalidad='" + nacionalidad + '\'' +
                ", fIniOpers='" + fIniOpers + '\'' +
                ", cSitCont='" + cSitCont + '\'' +
                ", cDetSitCont='" + cDetSitCont + '\'' +
                ", dSitCont='" + dSitCont + '\'' +
                ", fSitCont='" + fSitCont + '\'' +
                ", cSitDom='" + cSitDom + '\'' +
                ", dSitDom='" + dSitDom + '\'' +
                ", cSitContDom='" + cSitContDom + '\'' +
                ", dSitContDom='" + dSitContDom + '\'' +
                ", paisOrigen='" + paisOrigen + '\'' +
                ", dfTipo='" + dfTipo + '\'' +
                ", dfFolio='" + dfFolio + '\'' +
                ", dffInicio='" + dffInicio + '\'' +
                ", dffFin='" + dffFin + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
