//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.idc.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.idc.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatosEntrada }
     * 
     */
    public DatosEntrada createDatosEntrada() {
        return new DatosEntrada();
    }

    /**
     * Create an instance of {@link IdCInterno }
     * 
     */
    public IdCInterno createIdCInterno() {
        return new IdCInterno();
    }

    /**
     * Create an instance of {@link Identificacion }
     * 
     */
    public Identificacion createIdentificacion() {
        return new Identificacion();
    }

    /**
     * Create an instance of {@link Ubicacion }
     * 
     */
    public Ubicacion createUbicacion() {
        return new Ubicacion();
    }

    /**
     * Create an instance of {@link Obligacion }
     * 
     */
    public Obligacion createObligacion() {
        return new Obligacion();
    }

    /**
     * Create an instance of {@link Regimen }
     * 
     */
    public Regimen createRegimen() {
        return new Regimen();
    }

    /**
     * Create an instance of {@link Rol }
     * 
     */
    public Rol createRol() {
        return new Rol();
    }

    /**
     * Create an instance of {@link Actividad }
     * 
     */
    public Actividad createActividad() {
        return new Actividad();
    }

    /**
     * Create an instance of {@link RepLegal }
     * 
     */
    public RepLegal createRepLegal() {
        return new RepLegal();
    }

    /**
     * Create an instance of {@link Sucursal }
     * 
     */
    public Sucursal createSucursal() {
        return new Sucursal();
    }

    /**
     * Create an instance of {@link Mensajes }
     * 
     */
    public Mensajes createMensajes() {
        return new Mensajes();
    }

    /**
     * Create an instance of {@link GrupoEmpresa }
     * 
     */
    public GrupoEmpresa createGrupoEmpresa() {
        return new GrupoEmpresa();
    }

    /**
     * Create an instance of {@link Relacion }
     * 
     */
    public Relacion createRelacion() {
        return new Relacion();
    }

    /**
     * Create an instance of {@link RfcHistorico }
     * 
     */
    public RfcHistorico createRfcHistorico() {
        return new RfcHistorico();
    }

    /**
     * Create an instance of {@link Patente }
     * 
     */
    public Patente createPatente() {
        return new Patente();
    }

    /**
     * Create an instance of {@link Sector }
     * 
     */
    public Sector createSector() {
        return new Sector();
    }

}
