//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obligacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obligacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="c_Obligacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Obligacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_Alta_Oblig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_Baja_Oblig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_Efec_A_Oblig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_Efec_B_Oblig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_ini_Legal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_fin_Legal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="t_Contribucion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cve_pago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="d_oblig_lc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obligacion", propOrder = {
    "cObligacion",
    "dObligacion",
    "fAltaOblig",
    "fBajaOblig",
    "fEfecAOblig",
    "fEfecBOblig",
    "fIniLegal",
    "fFinLegal",
    "tContribucion",
    "cvePago",
    "dObligLc"
})
public class Obligacion {

    @XmlElement(name = "c_Obligacion", required = true)
    private String cObligacion;
    @XmlElement(name = "d_Obligacion", required = true)
    private String dObligacion;
    @XmlElement(name = "f_Alta_Oblig", required = true)
    private String fAltaOblig;
    @XmlElement(name = "f_Baja_Oblig", required = true)
    private String fBajaOblig;
    @XmlElement(name = "f_Efec_A_Oblig", required = true)
    private String fEfecAOblig;
    @XmlElement(name = "f_Efec_B_Oblig", required = true)
    private String fEfecBOblig;
    @XmlElement(name = "f_ini_Legal")
    private String fIniLegal;
    @XmlElement(name = "f_fin_Legal")
    private String fFinLegal;
    @XmlElement(name = "t_Contribucion")
    private String tContribucion;
    @XmlElement(name = "cve_pago")
    private String cvePago;
    @XmlElement(name = "d_oblig_lc")
    private String dObligLc;

    /**
     * Gets the value of the cObligacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCObligacion() {
        return cObligacion;
    }

    /**
     * Sets the value of the cObligacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCObligacion(String value) {
        this.cObligacion = value;
    }

    /**
     * Gets the value of the dObligacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDObligacion() {
        return dObligacion;
    }

    /**
     * Sets the value of the dObligacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDObligacion(String value) {
        this.dObligacion = value;
    }

    /**
     * Gets the value of the fAltaOblig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAltaOblig() {
        return fAltaOblig;
    }

    /**
     * Sets the value of the fAltaOblig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAltaOblig(String value) {
        this.fAltaOblig = value;
    }

    /**
     * Gets the value of the fBajaOblig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFBajaOblig() {
        return fBajaOblig;
    }

    /**
     * Sets the value of the fBajaOblig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFBajaOblig(String value) {
        this.fBajaOblig = value;
    }

    /**
     * Gets the value of the fEfecAOblig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEfecAOblig() {
        return fEfecAOblig;
    }

    /**
     * Sets the value of the fEfecAOblig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEfecAOblig(String value) {
        this.fEfecAOblig = value;
    }

    /**
     * Gets the value of the fEfecBOblig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEfecBOblig() {
        return fEfecBOblig;
    }

    /**
     * Sets the value of the fEfecBOblig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEfecBOblig(String value) {
        this.fEfecBOblig = value;
    }

    /**
     * Gets the value of the fIniLegal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIniLegal() {
        return fIniLegal;
    }

    /**
     * Sets the value of the fIniLegal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIniLegal(String value) {
        this.fIniLegal = value;
    }

    /**
     * Gets the value of the fFinLegal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFinLegal() {
        return fFinLegal;
    }

    /**
     * Sets the value of the fFinLegal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFinLegal(String value) {
        this.fFinLegal = value;
    }

    /**
     * Gets the value of the tContribucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTContribucion() {
        return tContribucion;
    }

    /**
     * Sets the value of the tContribucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTContribucion(String value) {
        this.tContribucion = value;
    }

    /**
     * Gets the value of the cvePago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvePago() {
        return cvePago;
    }

    /**
     * Sets the value of the cvePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvePago(String value) {
        this.cvePago = value;
    }

    /**
     * Gets the value of the dObligLc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDObligLc() {
        return dObligLc;
    }

    /**
     * Sets the value of the dObligLc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDObligLc(String value) {
        this.dObligLc = value;
    }

    @Override
    public String toString() {
        return "Obligacion{" +
                "cObligacion='" + cObligacion + '\'' +
                ", dObligacion='" + dObligacion + '\'' +
                ", fAltaOblig='" + fAltaOblig + '\'' +
                ", fBajaOblig='" + fBajaOblig + '\'' +
                ", fEfecAOblig='" + fEfecAOblig + '\'' +
                ", fEfecBOblig='" + fEfecBOblig + '\'' +
                ", fIniLegal='" + fIniLegal + '\'' +
                ", fFinLegal='" + fFinLegal + '\'' +
                ", tContribucion='" + tContribucion + '\'' +
                ", cvePago='" + cvePago + '\'' +
                ", dObligLc='" + dObligLc + '\'' +
                '}';
    }
}
