//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patente">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfc_agente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="n_agente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_ini_vigencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_fin_vigencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patente", propOrder = {
    "patente",
    "rfcAgente",
    "nAgente",
    "fIniVigencia",
    "fFinVigencia"
})
public class Patente {

    @XmlElement(required = true)
    private String patente;
    @XmlElement(name = "rfc_agente", required = true)
    private String rfcAgente;
    @XmlElement(name = "n_agente", required = true)
    private String nAgente;
    @XmlElement(name = "f_ini_vigencia", required = true)
    private String fIniVigencia;
    @XmlElement(name = "f_fin_vigencia", required = true)
    private String fFinVigencia;

    /**
     * Gets the value of the patente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatente() {
        return patente;
    }

    /**
     * Sets the value of the patente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatente(String value) {
        this.patente = value;
    }

    /**
     * Gets the value of the rfcAgente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcAgente() {
        return rfcAgente;
    }

    /**
     * Sets the value of the rfcAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcAgente(String value) {
        this.rfcAgente = value;
    }

    /**
     * Gets the value of the nAgente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAgente() {
        return nAgente;
    }

    /**
     * Sets the value of the nAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAgente(String value) {
        this.nAgente = value;
    }

    /**
     * Gets the value of the fIniVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIniVigencia() {
        return fIniVigencia;
    }

    /**
     * Sets the value of the fIniVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIniVigencia(String value) {
        this.fIniVigencia = value;
    }

    /**
     * Gets the value of the fFinVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFinVigencia() {
        return fFinVigencia;
    }

    /**
     * Sets the value of the fFinVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFinVigencia(String value) {
        this.fFinVigencia = value;
    }

    @Override
    public String toString() {
        return "Patente{" +
                "patente='" + patente + '\'' +
                ", rfcAgente='" + rfcAgente + '\'' +
                ", nAgente='" + nAgente + '\'' +
                ", fIniVigencia='" + fIniVigencia + '\'' +
                ", fFinVigencia='" + fFinVigencia + '\'' +
                '}';
    }
}
