//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="t_Relacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_inicio_rfc_Vig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfc_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombre_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ap_Paterno_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ap_Materno_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Razon_Soc_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="t_Soc_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_inicio_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_fin_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_Rol_Relacionante" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Rol_Relacionante" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="c_Rol_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="d_Rol_Relacionado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relacion", propOrder = {
    "tRelacion",
    "fInicioRfcVig",
    "rfcRelacionado",
    "nombreRelacionado",
    "apPaternoRelacionado",
    "apMaternoRelacionado",
    "razonSocRelacionado",
    "tSocRelacionado",
    "fInicioRelacionado",
    "fFinRelacionado",
    "cRolRelacionante",
    "dRolRelacionante",
    "cRolRelacionado",
    "dRolRelacionado"
})
public class Relacion {

    @XmlElement(name = "t_Relacion", required = true)
    private String tRelacion;
    @XmlElement(name = "f_inicio_rfc_Vig", required = true)
    private String fInicioRfcVig;
    @XmlElement(name = "rfc_Relacionado", required = true)
    private String rfcRelacionado;
    @XmlElement(name = "nombre_Relacionado", required = true)
    private String nombreRelacionado;
    @XmlElement(name = "Ap_Paterno_Relacionado", required = true)
    private String apPaternoRelacionado;
    @XmlElement(name = "Ap_Materno_Relacionado", required = true)
    private String apMaternoRelacionado;
    @XmlElement(name = "Razon_Soc_Relacionado", required = true)
    private String razonSocRelacionado;
    @XmlElement(name = "t_Soc_Relacionado", required = true)
    private String tSocRelacionado;
    @XmlElement(name = "f_inicio_Relacionado", required = true)
    private String fInicioRelacionado;
    @XmlElement(name = "f_fin_Relacionado", required = true)
    private String fFinRelacionado;
    @XmlElement(name = "c_Rol_Relacionante", required = true)
    private String cRolRelacionante;
    @XmlElement(name = "d_Rol_Relacionante", required = true)
    private String dRolRelacionante;
    @XmlElement(name = "c_Rol_Relacionado", required = true)
    private String cRolRelacionado;
    @XmlElement(name = "d_Rol_Relacionado", required = true)
    private String dRolRelacionado;

    /**
     * Gets the value of the tRelacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRelacion() {
        return tRelacion;
    }

    /**
     * Sets the value of the tRelacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRelacion(String value) {
        this.tRelacion = value;
    }

    /**
     * Gets the value of the fInicioRfcVig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFInicioRfcVig() {
        return fInicioRfcVig;
    }

    /**
     * Sets the value of the fInicioRfcVig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFInicioRfcVig(String value) {
        this.fInicioRfcVig = value;
    }

    /**
     * Gets the value of the rfcRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcRelacionado() {
        return rfcRelacionado;
    }

    /**
     * Sets the value of the rfcRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcRelacionado(String value) {
        this.rfcRelacionado = value;
    }

    /**
     * Gets the value of the nombreRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreRelacionado() {
        return nombreRelacionado;
    }

    /**
     * Sets the value of the nombreRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreRelacionado(String value) {
        this.nombreRelacionado = value;
    }

    /**
     * Gets the value of the apPaternoRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApPaternoRelacionado() {
        return apPaternoRelacionado;
    }

    /**
     * Sets the value of the apPaternoRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApPaternoRelacionado(String value) {
        this.apPaternoRelacionado = value;
    }

    /**
     * Gets the value of the apMaternoRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApMaternoRelacionado() {
        return apMaternoRelacionado;
    }

    /**
     * Sets the value of the apMaternoRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApMaternoRelacionado(String value) {
        this.apMaternoRelacionado = value;
    }

    /**
     * Gets the value of the razonSocRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazonSocRelacionado() {
        return razonSocRelacionado;
    }

    /**
     * Sets the value of the razonSocRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazonSocRelacionado(String value) {
        this.razonSocRelacionado = value;
    }

    /**
     * Gets the value of the tSocRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSocRelacionado() {
        return tSocRelacionado;
    }

    /**
     * Sets the value of the tSocRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSocRelacionado(String value) {
        this.tSocRelacionado = value;
    }

    /**
     * Gets the value of the fInicioRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFInicioRelacionado() {
        return fInicioRelacionado;
    }

    /**
     * Sets the value of the fInicioRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFInicioRelacionado(String value) {
        this.fInicioRelacionado = value;
    }

    /**
     * Gets the value of the fFinRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFinRelacionado() {
        return fFinRelacionado;
    }

    /**
     * Sets the value of the fFinRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFinRelacionado(String value) {
        this.fFinRelacionado = value;
    }

    /**
     * Gets the value of the cRolRelacionante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRolRelacionante() {
        return cRolRelacionante;
    }

    /**
     * Sets the value of the cRolRelacionante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRolRelacionante(String value) {
        this.cRolRelacionante = value;
    }

    /**
     * Gets the value of the dRolRelacionante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRolRelacionante() {
        return dRolRelacionante;
    }

    /**
     * Sets the value of the dRolRelacionante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRolRelacionante(String value) {
        this.dRolRelacionante = value;
    }

    /**
     * Gets the value of the cRolRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRolRelacionado() {
        return cRolRelacionado;
    }

    /**
     * Sets the value of the cRolRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRolRelacionado(String value) {
        this.cRolRelacionado = value;
    }

    /**
     * Gets the value of the dRolRelacionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRolRelacionado() {
        return dRolRelacionado;
    }

    /**
     * Sets the value of the dRolRelacionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRolRelacionado(String value) {
        this.dRolRelacionado = value;
    }

    @Override
    public String toString() {
        return "Relacion{" +
                "tRelacion='" + tRelacion + '\'' +
                ", fInicioRfcVig='" + fInicioRfcVig + '\'' +
                ", rfcRelacionado='" + rfcRelacionado + '\'' +
                ", nombreRelacionado='" + nombreRelacionado + '\'' +
                ", apPaternoRelacionado='" + apPaternoRelacionado + '\'' +
                ", apMaternoRelacionado='" + apMaternoRelacionado + '\'' +
                ", razonSocRelacionado='" + razonSocRelacionado + '\'' +
                ", tSocRelacionado='" + tSocRelacionado + '\'' +
                ", fInicioRelacionado='" + fInicioRelacionado + '\'' +
                ", fFinRelacionado='" + fFinRelacionado + '\'' +
                ", cRolRelacionante='" + cRolRelacionante + '\'' +
                ", dRolRelacionante='" + dRolRelacionante + '\'' +
                ", cRolRelacionado='" + cRolRelacionado + '\'' +
                ", dRolRelacionado='" + dRolRelacionado + '\'' +
                '}';
    }
}
