//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="c_Rol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="d_Rol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="d_Tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_Alta_Rol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="f_Baja_Rol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rol", propOrder = {
    "cRol",
    "dRol",
    "dTipo",
    "fAltaRol",
    "fBajaRol"
})
public class Rol {

    @XmlElement(name = "c_Rol")
    private String cRol;
    @XmlElement(name = "d_Rol")
    private String dRol;
    @XmlElement(name = "d_Tipo")
    private String dTipo;
    @XmlElement(name = "f_Alta_Rol")
    private String fAltaRol;
    @XmlElement(name = "f_Baja_Rol")
    private String fBajaRol;

    /**
     * Gets the value of the cRol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRol() {
        return cRol;
    }

    /**
     * Sets the value of the cRol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRol(String value) {
        this.cRol = value;
    }

    /**
     * Gets the value of the dRol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRol() {
        return dRol;
    }

    /**
     * Sets the value of the dRol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRol(String value) {
        this.dRol = value;
    }

    /**
     * Gets the value of the dTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTipo() {
        return dTipo;
    }

    /**
     * Sets the value of the dTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTipo(String value) {
        this.dTipo = value;
    }

    /**
     * Gets the value of the fAltaRol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAltaRol() {
        return fAltaRol;
    }

    /**
     * Sets the value of the fAltaRol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAltaRol(String value) {
        this.fAltaRol = value;
    }

    /**
     * Gets the value of the fBajaRol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFBajaRol() {
        return fBajaRol;
    }

    /**
     * Sets the value of the fBajaRol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFBajaRol(String value) {
        this.fBajaRol = value;
    }

    @Override
    public String toString() {
        return "Rol{" +
                "cRol='" + cRol + '\'' +
                ", dRol='" + dRol + '\'' +
                ", dTipo='" + dTipo + '\'' +
                ", fAltaRol='" + fAltaRol + '\'' +
                ", fBajaRol='" + fBajaRol + '\'' +
                '}';
    }
}
