//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:56:43 AM CST 
//


package mx.gob.sat.mat.rfcampl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sector">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sector_especifico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombre_sector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_ini_vigencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_fin_vigencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sector", propOrder = {
    "sectorEspecifico",
    "nombreSector",
    "fIniVigencia",
    "fFinVigencia"
})
public class Sector {

    @XmlElement(name = "sector_especifico", required = true)
    private String sectorEspecifico;
    @XmlElement(name = "nombre_sector", required = true)
    private String nombreSector;
    @XmlElement(name = "f_ini_vigencia", required = true)
    private String fIniVigencia;
    @XmlElement(name = "f_fin_vigencia", required = true)
    private String fFinVigencia;

    /**
     * Gets the value of the sectorEspecifico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectorEspecifico() {
        return sectorEspecifico;
    }

    /**
     * Sets the value of the sectorEspecifico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectorEspecifico(String value) {
        this.sectorEspecifico = value;
    }

    /**
     * Gets the value of the nombreSector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreSector() {
        return nombreSector;
    }

    /**
     * Sets the value of the nombreSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreSector(String value) {
        this.nombreSector = value;
    }

    /**
     * Gets the value of the fIniVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIniVigencia() {
        return fIniVigencia;
    }

    /**
     * Sets the value of the fIniVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIniVigencia(String value) {
        this.fIniVigencia = value;
    }

    /**
     * Gets the value of the fFinVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFinVigencia() {
        return fFinVigencia;
    }

    /**
     * Sets the value of the fFinVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFinVigencia(String value) {
        this.fFinVigencia = value;
    }

    @Override
    public String toString() {
        return "Sector{" +
                "sectorEspecifico='" + sectorEspecifico + '\'' +
                ", nombreSector='" + nombreSector + '\'' +
                ", fIniVigencia='" + fIniVigencia + '\'' +
                ", fFinVigencia='" + fFinVigencia + '\'' +
                '}';
    }
}
