//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for BusquedaTramitesManuales complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusquedaTramitesManuales">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosContribuyente" type="{http://ws.dyc.mat.sat.gob.mx/}DatosContribuyente"/>
 *         &lt;element name="DatosICEP" type="{http://ws.dyc.mat.sat.gob.mx/}DatosICEP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusquedaTramitesManuales", propOrder = {
    "datosContribuyente",
    "datosICEP"
})
@XmlRootElement(name = "BusquedaTramitesManuales")
public class BusquedaTramitesManuales {

    @XmlElement(name = "DatosContribuyente", required = true)
    private DatosContribuyente datosContribuyente;
    @XmlElement(name = "DatosICEP", required = true)
    private DatosICEP datosICEP;

    /**
     * Gets the value of the datosContribuyente property.
     * 
     * @return
     *     possible object is
     *     {@link DatosContribuyente }
     *     
     */
    public DatosContribuyente getDatosContribuyente() {
        return datosContribuyente;
    }

    /**
     * Sets the value of the datosContribuyente property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosContribuyente }
     *     
     */
    public void setDatosContribuyente(DatosContribuyente value) {
        this.datosContribuyente = value;
    }

    /**
     * Gets the value of the datosICEP property.
     * 
     * @return
     *     possible object is
     *     {@link DatosICEP }
     *     
     */
    public DatosICEP getDatosICEP() {
        return datosICEP;
    }

    /**
     * Sets the value of the datosICEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosICEP }
     *     
     */
    public void setDatosICEP(DatosICEP value) {
        this.datosICEP = value;
    }

}
