//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:18 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosTramite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosTramite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="origenSaldo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tipoTramite" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosTramite", propOrder = {
    "origenSaldo",
    "tipoTramite"
})
@XmlRootElement(name = "DatosTramite")
public class DatosTramite {

    @XmlElement(required = true)
    private BigInteger origenSaldo;
    @XmlElement(required = true)
    private BigInteger tipoTramite;

    /**
     * Gets the value of the origenSaldo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrigenSaldo() {
        return origenSaldo;
    }

    /**
     * Sets the value of the origenSaldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrigenSaldo(BigInteger value) {
        this.origenSaldo = value;
    }

    /**
     * Gets the value of the tipoTramite property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoTramite() {
        return tipoTramite;
    }

    /**
     * Sets the value of the tipoTramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoTramite(BigInteger value) {
        this.tipoTramite = value;
    }

    @Override
    public String toString() {
        return "DatosTramite{" +
                "origenSaldo=" + origenSaldo +
                ", tipoTramite=" + tipoTramite +
                '}';
    }
}
