//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.08 at 06:19:29 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DatosDevolucionAutomatica complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DatosDevolucionAutomatica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="importeSolicitado" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosDevolucionAutomatica", propOrder = {
    "importeSolicitado"
})
@XmlRootElement(name = "DatosDevolucionAutomatica")
public class DatosDevolucionAutomatica {

    @XmlElement(required = true, nillable = true)
    private BigDecimal importeSolicitado;

    /**
     * Gets the value of the importeSolicitado property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getImporteSolicitado() {
        return importeSolicitado;
    }

    /**
     * Sets the value of the importeSolicitado property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteSolicitado(BigDecimal value) {
        this.importeSolicitado = value;
    }

}
