//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:18 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DatosDeclaracion complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DatosDeclaracion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoDeclaracion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="fechaPresentacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="numOperacion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="importeSaldoAFavor" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosDeclaracion", propOrder = {
    "tipoDeclaracion",
    "fechaPresentacion",
    "numOperacion",
    "importeSaldoAFavor"
})
@XmlRootElement(name = "DatosDeclaracion")
public class DatosDeclaracion {

    @XmlElement(required = true)
    private BigInteger tipoDeclaracion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar fechaPresentacion;
    @XmlElement(required = true)
    private BigInteger numOperacion;
    @XmlElement(required = true)
    private BigDecimal importeSaldoAFavor;

    /**
     * Gets the value of the tipoDeclaracion property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getTipoDeclaracion() {
        return tipoDeclaracion;
    }

    /**
     * Sets the value of the tipoDeclaracion property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setTipoDeclaracion(BigInteger value) {
        this.tipoDeclaracion = value;
    }

    /**
     * Gets the value of the fechaPresentacion property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFechaPresentacion() {
        return fechaPresentacion;
    }

    /**
     * Sets the value of the fechaPresentacion property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFechaPresentacion(XMLGregorianCalendar value) {
        this.fechaPresentacion = value;
    }

    /**
     * Gets the value of the numOperacion property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getNumOperacion() {
        return numOperacion;
    }

    /**
     * Sets the value of the numOperacion property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setNumOperacion(BigInteger value) {
        this.numOperacion = value;
    }

    /**
     * Gets the value of the importeSaldoAFavor property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getImporteSaldoAFavor() {
        return importeSaldoAFavor;
    }

    /**
     * Sets the value of the importeSaldoAFavor property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteSaldoAFavor(BigDecimal value) {
        this.importeSaldoAFavor = value;
    }

    @Override
    public String toString() {
        return "DatosDeclaracion{"
                + "tipoDeclaracion=" + tipoDeclaracion
                + ", fechaPresentacion=" + fechaPresentacion
                + ", numOperacion=" + numOperacion
                + ", importeSaldoAFavor=" + importeSaldoAFavor
                + '}';
    }

}
