//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosICEP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosICEP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="impuesto" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="concepto" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ejercicio" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosICEP", propOrder = {
    "impuesto",
    "concepto",
    "ejercicio",
    "periodo"
})
@XmlRootElement(name = "DatosICEP")
public class DatosICEP {

    @XmlElement(required = true)
    private BigInteger impuesto;
    @XmlElement(required = true)
    private BigInteger concepto;
    @XmlElement(required = true)
    private BigInteger ejercicio;
    @XmlElement(required = true)
    private String periodo;

    /**
     * Gets the value of the impuesto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getImpuesto() {
        return impuesto;
    }

    /**
     * Sets the value of the impuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setImpuesto(BigInteger value) {
        this.impuesto = value;
    }

    /**
     * Gets the value of the concepto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConcepto() {
        return concepto;
    }

    /**
     * Sets the value of the concepto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConcepto(BigInteger value) {
        this.concepto = value;
    }

    /**
     * Gets the value of the ejercicio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEjercicio() {
        return ejercicio;
    }

    /**
     * Sets the value of the ejercicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEjercicio(BigInteger value) {
        this.ejercicio = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodo(String value) {
        this.periodo = value;
    }

    @Override
    public String toString() {
        return "DatosICEP{" +
                "impuesto=" + impuesto +
                ", concepto=" + concepto +
                ", ejercicio=" + ejercicio +
                ", periodo='" + periodo + '\'' +
                '}';
    }
}
