//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosRegistroMATDYC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosRegistroMATDYC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="folioMATDYC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IDICEP" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="saldoICEP" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosRegistroMATDYC", propOrder = {
    "folioMATDYC",
    "idicep",
    "saldoICEP",
    "importeResuelto"
})
@XmlRootElement(name = "DatosRegistroMATDYC")
public class DatosRegistroMATDYC {

    @XmlElement(name="folioMATDYC", required = true, nillable = true)
    private String folioMATDYC;
    @XmlElement(name = "IDICEP", required = true, nillable = true)
    private BigInteger idicep;
    @XmlElement(name="saldoICEP", required = true, nillable = true)
    private BigDecimal saldoICEP;
    @XmlElement(name = "importeResuelto", required = true)
    private BigDecimal importeResuelto;

    /**
     * Gets the value of the folioMATDYC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioMATDYC() {
        return folioMATDYC;
    }

    /**
     * Sets the value of the folioMATDYC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioMATDYC(String value) {
        this.folioMATDYC = value;
    }

    /**
     * Gets the value of the idicep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDICEP() {
        return idicep;
    }

    /**
     * Sets the value of the idicep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDICEP(BigInteger value) {
        this.idicep = value;
    }

    /**
     * Gets the value of the saldoICEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoICEP() {
        return saldoICEP;
    }

    /**
     * Sets the value of the saldoICEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoICEP(BigDecimal value) {
        this.saldoICEP = value;
    }

    public BigDecimal getImporteResuelto() {
        return importeResuelto;
    }

    public void setImporteResuelto(BigDecimal importeResuelto) {
        this.importeResuelto = importeResuelto;
    }
}
