//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:37:55 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for NotificacionConfirAutoPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificacionConfirAutoPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstadoActualizacion" type="{http://ws.dyc.mat.sat.gob.mx/}EstadoActualizacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificacionConfirAutoPago", propOrder = {
    "estadoActualizacion"
})
@XmlRootElement(name = "NotificacionConfirAutoPago")
public class NotificacionConfirAutoPago {

    @XmlElement(name = "EstadoActualizacion", required = true)
    private EstadoActualizacion estadoActualizacion;

    /**
     * Gets the value of the estadoActualizacion property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoActualizacion }
     *     
     */
    public EstadoActualizacion getEstadoActualizacion() {
        return estadoActualizacion;
    }

    /**
     * Sets the value of the estadoActualizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoActualizacion }
     *     
     */
    public void setEstadoActualizacion(EstadoActualizacion value) {
        this.estadoActualizacion = value;
    }

}
