//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for NotificacionConsulSolIRS complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NotificacionConsulSolIRS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosContribuyente" type="{http://ws.dyc.mat.sat.gob.mx/}DatosContribuyente"/>
 *         &lt;element name="DatosRegistroMATDYC" type="{http://ws.dyc.mat.sat.gob.mx/}DatosRegistroMATDYC"/>
 *         &lt;element name="DatosSolicitud" type="{http://ws.dyc.mat.sat.gob.mx/}DatosSolicitud"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificacionConsulSolIRS", propOrder = {
    "datosContribuyente",
    "datosRegistroMATDYC",
    "datosSolicitud"
})
@XmlRootElement(name = "NotificacionConsulSolIRS")
public class NotificacionConsulSolIRS {

    @XmlElement(name = "DatosContribuyente", required = true)
    private DatosContribuyente datosContribuyente;
    @XmlElement(name = "DatosRegistroMATDYC", required = true)
    private DatosRegistroMATDYC datosRegistroMATDYC;
    @XmlElement(name = "DatosSolicitud", required = true)
    private DatosSolicitud datosSolicitud;

    /**
     * Gets the value of the datosContribuyente property.
     *
     * @return possible object is {@link DatosContribuyente }
     *
     */
    public DatosContribuyente getDatosContribuyente() {
        return datosContribuyente;
    }

    /**
     * Sets the value of the datosContribuyente property.
     *
     * @param value allowed object is {@link DatosContribuyente }
     *
     */
    public void setDatosContribuyente(DatosContribuyente value) {
        this.datosContribuyente = value;
    }

    /**
     * Gets the value of the datosRegistroMATDYC property.
     *
     * @return possible object is {@link DatosRegistroMATDYC }
     *
     */
    public DatosRegistroMATDYC getDatosRegistroMATDYC() {
        return datosRegistroMATDYC;
    }

    /**
     * Sets the value of the datosRegistroMATDYC property.
     *
     * @param value allowed object is {@link DatosRegistroMATDYC }
     *
     */
    public void setDatosRegistroMATDYC(DatosRegistroMATDYC value) {
        this.datosRegistroMATDYC = value;
    }

    /**
     * Gets the value of the datosSolicitud property.
     *
     * @return possible object is {@link DatosSolicitud }
     *
     */
    public DatosSolicitud getDatosSolicitud() {
        return datosSolicitud;
    }

    /**
     * Sets the value of the datosSolicitud property.
     *
     * @param value allowed object is {@link DatosSolicitud }
     *
     */
    public void setDatosSolicitud(DatosSolicitud value) {
        this.datosSolicitud = value;
    }

}
