//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.08 at 04:48:58 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NotificacionRegistroYGestion complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NotificacionRegistroYGestion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="edoDeLaOperacion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="folioMATDYC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idICEP" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="remanenteICEPAntesDeCargo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="importeResueltoAntesDeCargo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="importeNetoADevolver" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="motivo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tipoDeResolucion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="importeAutorizado" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="remanenteICEPDespuesDeCargo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="importeResueltoDespuesDeCargo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificacionRegistroYGestion", propOrder = {
    "edoDeLaOperacion",
    "folioMATDYC",
    "idICEP",
    "remanenteICEPAntesDeCargo",
    "importeResueltoAntesDeCargo",
    "importeNetoADevolver",
    "motivo",
    "tipoDeResolucion",
    "importeAutorizado",
    "remanenteICEPDespuesDeCargo",
    "importeResueltoDespuesDeCargo"
})
@XmlRootElement(name = "NotificacionRegistroYGestion")
public class NotificacionRegistroYGestion {

    @XmlElement(required = true, nillable = true)
    private BigInteger edoDeLaOperacion;
    @XmlElement(required = true, nillable = true)
    private String folioMATDYC;
    @XmlElement(required = true, nillable = true)
    private BigInteger idICEP;
    @XmlElement(required = true, nillable = true)
    private BigDecimal remanenteICEPAntesDeCargo;
    @XmlElement(required = true, nillable = true)
    private BigDecimal importeResueltoAntesDeCargo;
    @XmlElement(required = true, nillable = true)
    private BigDecimal importeNetoADevolver;
    @XmlElement(required = true, nillable = true)
    private BigInteger motivo;
    @XmlElement(required = true, nillable = true)
    private BigInteger tipoDeResolucion;
    @XmlElement(required = true, nillable = true)
    private BigDecimal importeAutorizado;
    @XmlElement(required = true, nillable = true)
    private BigDecimal remanenteICEPDespuesDeCargo;
    @XmlElement(required = true, nillable = true)
    private BigDecimal importeResueltoDespuesDeCargo;

    /**
     * Gets the value of the edoDeLaOperacion property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getEdoDeLaOperacion() {
        return edoDeLaOperacion;
    }

    /**
     * Sets the value of the edoDeLaOperacion property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setEdoDeLaOperacion(BigInteger value) {
        this.edoDeLaOperacion = value;
    }

    /**
     * Gets the value of the folioMATDYC property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFolioMATDYC() {
        return folioMATDYC;
    }

    /**
     * Sets the value of the folioMATDYC property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFolioMATDYC(String value) {
        this.folioMATDYC = value;
    }

    /**
     * Gets the value of the idICEP property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getIdICEP() {
        return idICEP;
    }

    /**
     * Sets the value of the idICEP property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setIdICEP(BigInteger value) {
        this.idICEP = value;
    }

    /**
     * Gets the value of the remanenteICEPAntesDeCargo property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigDecimal getRemanenteICEPAntesDeCargo() {
        return remanenteICEPAntesDeCargo;
    }

    /**
     * Sets the value of the remanenteICEPAntesDeCargo property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setRemanenteICEPAntesDeCargo(BigDecimal value) {
        this.remanenteICEPAntesDeCargo = value;
    }

    /**
     * Gets the value of the importeResueltoAntesDeCargo property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigDecimal getImporteResueltoAntesDeCargo() {
        return importeResueltoAntesDeCargo;
    }

    /**
     * Sets the value of the importeResueltoAntesDeCargo property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteResueltoAntesDeCargo(BigDecimal value) {
        this.importeResueltoAntesDeCargo = value;
    }

    /**
     * Gets the value of the importeNetoADevolver property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getImporteNetoADevolver() {
        return importeNetoADevolver;
    }

    /**
     * Sets the value of the importeNetoADevolver property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteNetoADevolver(BigDecimal value) {
        this.importeNetoADevolver = value;
    }

    /**
     * Gets the value of the motivo property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getMotivo() {
        return motivo;
    }

    /**
     * Sets the value of the motivo property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setMotivo(BigInteger value) {
        this.motivo = value;
    }

    /**
     * Gets the value of the tipoDeResolucion property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getTipoDeResolucion() {
        return tipoDeResolucion;
    }

    /**
     * Sets the value of the tipoDeResolucion property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setTipoDeResolucion(BigInteger value) {
        this.tipoDeResolucion = value;
    }

    /**
     * Gets the value of the importeAutorizado property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getImporteAutorizado() {
        return importeAutorizado;
    }

    /**
     * Sets the value of the importeAutorizado property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteAutorizado(BigDecimal value) {
        this.importeAutorizado = value;
    }

    /**
     * Gets the value of the remanenteICEPDespuesDeCargo property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getRemanenteICEPDespuesDeCargo() {
        return remanenteICEPDespuesDeCargo;
    }

    /**
     * Sets the value of the remanenteICEPDespuesDeCargo property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setRemanenteICEPDespuesDeCargo(BigDecimal value) {
        this.remanenteICEPDespuesDeCargo = value;
    }

    /**
     * Gets the value of the importeResueltoDespuesDeCargo property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getImporteResueltoDespuesDeCargo() {
        return importeResueltoDespuesDeCargo;
    }

    /**
     * Sets the value of the importeResueltoDespuesDeCargo property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setImporteResueltoDespuesDeCargo(BigDecimal value) {
        this.importeResueltoDespuesDeCargo = value;
    }

}
