//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the mx.gob.sat.mat.dyc.ws.domain package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: mx.gob.sat.mat.dyc.ws.domain
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarSolCompIRSDevAut }
     *
     */
    public ConsultarSolCompIRSDevAut createConsultarSolCompIRSDevAut() {
        return new ConsultarSolCompIRSDevAut();
    }

    /**
     * Create an instance of {@link BusquedaTramitesManuales }
     *
     */
    public BusquedaTramitesManuales createBusquedaTramitesManuales() {
        return new BusquedaTramitesManuales();
    }

    /**
     * Create an instance of {@link ConsultarSolCompIRSDevAutResponse }
     *
     */
    public ConsultarSolCompIRSDevAutResponse createConsultarSolCompIRSDevAutResponse() {
        return new ConsultarSolCompIRSDevAutResponse();
    }

    /**
     * Create an instance of {@link NotificacionConsulSolIRS }
     *
     */
    public NotificacionConsulSolIRS createNotificacionConsulSolIRS() {
        return new NotificacionConsulSolIRS();
    }

    /**
     * Create an instance of {@link DatosRegistroMATDYC }
     *
     */
    public DatosRegistroMATDYC createDatosRegistroMATDYC() {
        return new DatosRegistroMATDYC();
    }

    /**
     * Create an instance of {@link DatosContribuyente }
     *
     */
    public DatosContribuyente createDatosContribuyente() {
        return new DatosContribuyente();
    }

    /**
     * Create an instance of {@link DatosICEP }
     *
     */
    public DatosICEP createDatosICEP() {
        return new DatosICEP();
    }

    /**
     * Create an instance of {@link DatosSolicitud }
     *
     */
    public DatosSolicitud createDatosSolicitud() {
        return new DatosSolicitud();
    }

    /**
     * Create an instance of {@link RepcionYGestTramDevAutISRResponse }
     *
     */
    public RepcionYGestTramDevAutISRResponse createRepcionYGestTramDevAutISRResponse() {
        return new RepcionYGestTramDevAutISRResponse();
    }

    /**
     * Create an instance of {@link NotificacionRegistroYGestion }
     *
     */
    public NotificacionRegistroYGestion createNotificacionRegistroYGestion() {
        return new NotificacionRegistroYGestion();
    }

    /**
     * Create an instance of {@link RepcionYGestTramDevAutISR }
     *
     */
    public RepcionYGestTramDevAutISR createRepcionYGestTramDevAutISR() {
        return new RepcionYGestTramDevAutISR();
    }

    /**
     * Create an instance of {@link RegistroYGestionDevAut }
     *
     */
    public RegistroYGestionDevAut createRegistroYGestionDevAut() {
        return new RegistroYGestionDevAut();
    }

    /**
     * Create an instance of {@link InfoBanco }
     *
     */
    public InfoBanco createInfoBanco() {
        return new InfoBanco();
    }

    /**
     * Create an instance of {@link DatosTramite }
     *
     */
    public DatosTramite createDatosTramite() {
        return new DatosTramite();
    }

    /**
     * Create an instance of {@link DatosDeclaracion }
     *
     */
    public DatosDeclaracion createDatosDeclaracion() {
        return new DatosDeclaracion();
    }

    /**
     * Create an instance of {@link VerificaDevManual }
     *
     */
    public VerificaDevManual createVerificaDevManual() {
        return new VerificaDevManual();
    }

    /**
     * Create an instance of {@link RegistroDevolucionAut }
     *
     */
    public RegistroDevolucionAut createRegistroDevolucionAut() {
        return new RegistroDevolucionAut();
    }

    /**
     * Create an instance of {@link VerificaDevManualResponse }
     *
     */
    public VerificaDevManualResponse createVerificaDevManualResponse() {
        return new VerificaDevManualResponse();
    }

    /**
     * Create an instance of {@link NotificacionVeriDevManual }
     *
     */
    public NotificacionVeriDevManual createNotificacionVeriDevManual() {
        return new NotificacionVeriDevManual();
    }

    /**
     * Create an instance of {@link DatosDevolucionAutomatica }
     *
     */
    public DatosDevolucionAutomatica createDatosDevolucionAutomatica() {
        return new DatosDevolucionAutomatica();
    }

}
