//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:32 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.dyc.mat.sat.gob.mx/")
package mx.gob.sat.mat.dyc.ws.domain;
