//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.08 at 04:48:58 PM CST 
//
package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegistroYGestionDevAut" type="{http://ws.dyc.mat.sat.gob.mx/}RegistroYGestionDevAut"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registroYGestionDevAut"
})
@XmlRootElement(name = "repcionYGestTramDevAutISR")
public class RepcionYGestTramDevAutISR {

    @XmlElement(name = "RegistroYGestionDevAut", required = true)
    private RegistroYGestionDevAut registroYGestionDevAut;

    /**
     * Gets the value of the registroYGestionDevAut property.
     *
     * @return possible object is {@link RegistroYGestionDevAut }
     *
     */
    public RegistroYGestionDevAut getRegistroYGestionDevAut() {
        return registroYGestionDevAut;
    }

    /**
     * Sets the value of the registroYGestionDevAut property.
     *
     * @param value allowed object is {@link RegistroYGestionDevAut }
     *
     */
    public void setRegistroYGestionDevAut(RegistroYGestionDevAut value) {
        this.registroYGestionDevAut = value;
    }

}
