//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:38:18 PM CST 
//


package mx.gob.sat.mat.dyc.ws.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NotificacionVeriDevManual" type="{http://ws.dyc.mat.sat.gob.mx/}NotificacionVeriDevManual"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificacionVeriDevManual"
})
@XmlRootElement(name = "verificaDevManualResponse")
public class VerificaDevManualResponse {

    @XmlElement(name = "NotificacionVeriDevManual", required = true)
    private NotificacionVeriDevManual notificacionVeriDevManual;

    /**
     * Gets the value of the notificacionVeriDevManual property.
     * 
     * @return
     *     possible object is
     *     {@link NotificacionVeriDevManual }
     *     
     */
    public NotificacionVeriDevManual getNotificacionVeriDevManual() {
        return notificacionVeriDevManual;
    }

    /**
     * Sets the value of the notificacionVeriDevManual property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificacionVeriDevManual }
     *     
     */
    public void setNotificacionVeriDevManual(NotificacionVeriDevManual value) {
        this.notificacionVeriDevManual = value;
    }

}
