
package mx.gob.sat.siat.dyc.tesofe.service.cliente;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RetroalimentaPagoMATDyCServiceImpl", targetNamespace = "http://impl.services.matdyc.retropago.pf.isr.sad.dyc.sat.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RetroalimentaPagoMATDyCServiceImpl {


    /**
     * 
     * @param retroalimentaPagoIn
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "retroalimentaPago", targetNamespace = "http://impl.services.matdyc.retropago.pf.isr.sad.dyc.sat.gob.mx/", className = "mx.gob.sat.siat.dyc.tesofe.service.cliente.RetroalimentaPago")
    void retroalimentaPago(
        @WebParam(name = "retroalimentaPagoIn", targetNamespace = "")
        RetroalimentaPagoMATDyCIn retroalimentaPagoIn);

}
